---
- name: Install latest docker version while Ubuntu
  ansible.builtin.apt:
    name: "{{ item }}"
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
  when:
    - ansible_facts['os_family'] == "Debian"
# Prepare RedHat based systems
- name: Install Docker Repo while RedHat
  ansible.builtin.yum:
    name: yum-utils
    state: installed
  when:
    - ansible_facts['os_family'] == "RedHat"
- name: Configure Docker Repo
  ansible.builtin.command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  when:
    - ansible_facts['os_family'] == "RedHat"
- name: Install Docker rpms
  ansible.builtin.yum:
    name: "{{ item }}"
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
  notify:
    - start_docker
  when:
  - ansible_facts['os_family'] == "RedHat"