---
- name: Uninstall old Docker versions
  ansible.builtin.import_tasks:
    file: 1_uninstall_old_docker.yml
- name: Setup Docker repo on Ubuntu
  ansible.builtin.import_tasks:
    file: 2_setup_ubuntu_docker_repo.yml
- name: Install latest Docker
  ansible.builtin.import_tasks:
    file: 3_install_latest_docker.yml