---
# Uninstall old Versions
- name: Uninstall old versions while Debian
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker-engine
    - docker.io
    - containerd
    - runc
  when:
    - ansible_facts['os_family'] == "Debian"
- name: Uninstall old versions while Centos
  ansible.builtin.yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker
    - docker-client
    - docker-client-latest
    - docker-common
    - docker-latest
    - docker-latest-logrotate
    - docker-logrotate
    - docker-engine
  when:
    - ansible_facts['os_family'] == "RedHat"
# Setup Docker repo
- name:  Install required pkgs while Ubuntu
  ansible.builtin.apt:
    name: "{{ item }}"
  with_items:
    - ca-certificates
    - curl
    - gnupg
    - python3-apt
  when:
    - ansible_facts['os_family'] == "Debian"
- name: Add Docker’s official GPG key
  ansible.builtin.command:
    cmd:
      - sudo install -m 0755 -d /etc/apt/keyrings
  when:
    - ansible_facts['os_family'] == "Debian"