---
- name: Copy script
  ansible.builtin.copy:
    src: files/tmp/apt_pgsql_config.sh
    dest: /tmp/apt_pgsql_config.sh
  when:
    - ansible_facts['os_family'] == "Debian"
- name: Execute Script
  ansible.builtin.shell: sh /tmp/apt_pgsql_config.sh
  when:
    - ansible_facts['os_family'] == "Debian"